<a href="https://colab.research.google.com/github/AnakhaNami/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 18-09-2025


import numpy as np # numerical python

# array

a=np.array([1,2,3,4])
print(a)
b=np.array([1,2,3.0,4])      # all changes into float
print(b)
c=np.array([1,2,3,4,"a"])    # all changes into string
print(c)

[1 2 3 4]
[1. 2. 3. 4.]
['1' '2' '3' '4' 'a']


In [ ]:
# slicing - forward slicing, background slicing

a=np.array([1,2,3,4,5])
# print 1,2
print(a[0:2:1])
# print 5,4
print(a[-1:-3:-1])
#print 4,5
print(a[3:])
# print 2,1
print(a[-4: :-1])

[1 2]
[5 4]
[4 5]
[2 1]


In [ ]:
 # Dimension

 a=np.array([0,1,2,3,4,5])
 b=np.array([[1,2],[3,4]])

 print(a.ndim)  # dimension=1 then its a vector
 print(b.ndim)  # dimension=2 then matrix - 2d array=matrix, if 2 square bracket then 2 d array
 print(a)
 print(b)
 b.shape  # to identify rows and cloum

1
2
[0 1 2 3 4 5]
[[1 2]
 [3 4]]


(2, 2)

In [ ]:
# create a 2X2 matrix 2,3,4,5

a=np.array([[2,3],[4,5]])
print(a)
print(a.shape)
print(a.ndim)

[[2 3]
 [4 5]]
(2, 2)
2


In [ ]:
#create a 2x3 matrix and print size,shape, dimension

a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.size)
print(a.shape)
print(a.ndim)

[[1 2 3]
 [4 5 6]]
6
(2, 3)
2


In [ ]:
# create 4x2 matrix display its size shape dimension

a=np.array([[1,2],[3,4],[5,6],[7,8]])
print(a)
print(a.size)
print(a.shape)
print(a.ndim)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
8
(4, 2)
2


In [ ]:
#19-09-2025

#create 4x4 matrix

a=np.array([[1,2,3,4],[5,3,2,2],[7,6,5,3],[3,4,3,2]])
print(a)


[[1 2 3 4]
 [5 3 2 2]
 [7 6 5 3]
 [3 4 3 2]]


In [ ]:
print(a[0])
print(a[:,0])
print(a[1,1])
print(a[2,2])

[1 2 3 4]
[1 5 7 3]
3
5


In [ ]:
print(a[3,2:])
print(a[2:,2:])


[3 2]
[[5 3]
 [3 2]]


In [ ]:
print(a[2:,1:3])

[[6 5]
 [4 3]]


In [ ]:
print(a[1:3,3])

[2 3]


In [ ]:
print(a[1:3,0:3])

[[5 3 2]
 [7 6 5]]


In [ ]:
print(a[0:3,1:])

[[2 3 4]
 [3 2 2]
 [6 5 3]]


In [ ]:
print(a[1:,0:])

[[5 3 2 2]
 [7 6 5 3]
 [3 4 3 2]]


In [2]:
print(a[0:,1:2])

NameError: name 'a' is not defined

In [ ]:
print(a[0:,0:])

[[1 2 3 4]
 [5 3 2 2]
 [7 6 5 3]
 [3 4 3 2]]


In [ ]:

#zero matrix

import numpy as np
z=np.zeros([3,3])   # 3x3 matrix
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np
z=np.zeros([3,3,3])    # 3 3x3 matri
print(z)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
import numpy as np
z=np.zeros([3,3,3],dtype=complex)   # complex - to change datatype into complex
z

array([[[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]]])

In [ ]:
import numpy as np
z=np.zeros([2,3,3],dtype=int)
z

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [ ]:
# one matrix

z=np.ones([3,3],dtype=int)
z

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
# create two 2x2 matrix

a=np.array([[1,2],[3,4]])
b=np.array([[3,1],[6,7]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[3 1]
 [6 7]]


In [ ]:
#matrix addition
print((a+b))

[[ 4  3]
 [ 9 11]]


In [ ]:
#matrix substraction
print((a-b))

[[-2  1]
 [-3 -3]]


In [ ]:
#matrix multiplication

#print(a*b)  #not a matrix multiplication

print(a@b)

print(a.dot(b))

[[15 15]
 [33 31]]
[[15 15]
 [33 31]]


In [ ]:
#matrix divison

print(a/b)

[[0.33333333 2.        ]
 [0.5        0.57142857]]


In [ ]:
# magic
#  __add__ - function starting in underscore

In [ ]:
#full matrix   - all elements are same

z=np.full([3,3],5,dtype=int)
z

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
#create 3x4 matrix with value 9 and datatype complex
z=np.full([3,4],9,dtype=complex)
z

array([[9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j]])

In [ ]:
#identity matrix

z=np.identity(3,dtype=int)
z
#or
z=np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
# create a 4x4 matrix

y=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(y)
print(y.size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
16


In [ ]:
a=y.reshape(8,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [ ]:
# arange
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [ ]:
# create a 5x2 matrix using arange

a=np.arange(1,11).reshape(5,2)
a


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
# create a 3x3 matrix with float values

a=np.array([[2.5,3.6,3.5],[1.5,1.1,6.5],[7.1,2.5,7.1]])
a

array([[2.5, 3.6, 3.5],
       [1.5, 1.1, 6.5],
       [7.1, 2.5, 7.1]])

In [ ]:
# Floor

z=np.floor(a)
z


array([[2., 3., 3.],
       [1., 1., 6.],
       [7., 2., 7.]])

In [ ]:
# Ceil
z=np.ceil(a)
z


array([[3., 4., 4.],
       [2., 2., 7.],
       [8., 3., 8.]])

In [ ]:
# round
z=np.round(a)
z

array([[2., 4., 4.],
       [2., 1., 6.],
       [7., 2., 7.]])

In [9]:
# create a 3x3 matrix
import numpy as np
a=np.arange(1,10).reshape(3,3)
print(a)

print(a.max())
print(a.max(axis=1))
print(a.max(axis=0))
print(a.min())
print(a.min(axis=1))
print(a.min(axis=0))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
[3 6 9]
[7 8 9]
1
[1 4 7]
[1 2 3]


In [11]:
# 22-09-2025

print(a.sum())
print(a.sum(axis=1))
print(a.sum(axis=0))

45
[ 6 15 24]
[12 15 18]


In [13]:
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [15]:
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))


[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [17]:
# Flatten()

a.flatten()  # - to convert any dimension matrix to 1 dimension array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# SORT

# create 3x3 matrix
a=np.array([[3,4,1],[5,3,1],[6,9,8]])
print(a)

b=np.sort(a,axis=1)      # to sort each element in row.
print(b)

c=np.argsort(a,axis=1)   # to sort sorted matrix according to index
print(c)


[[3 4 1]
 [5 3 1]
 [6 9 8]]
[[1 3 4]
 [1 3 5]
 [6 8 9]]
[[2 0 1]
 [2 1 0]
 [0 2 1]]
